oop bank account
PdxCodeGuild/class_chihuahua pull request #39
Opened 2022-09-24 02:12 UTC by Helmer85

2022-09-24 03:28 UTC, cdmichaelb requested changes
Good work on OOP lab bank account and rectangle class. Person class still missing.

2022-09-29 03:09 UTC, AlexDeMichieli requested changes
Need changes before approval

2022-09-29 03:09 UTC, AlexDeMichieli commented on code/jeff/Python/oop_rectangle.py
> +
Missing the implementation of the Parallelepipede child class  . Lab description [here](https://github.com/PdxCodeGuild/class_chihuahua/blob/main/1%20Python/labs/OOP.md)

2022-10-07 03:32 UTC, AlexDeMichieli approved these changes

2022-10-07 03:32 UTC, merged