Rachel
PdxCodeGuild/class_chihuahua pull request #49
Opened 2022-09-28 03:48 UTC by rachellindsay

Added pick_6 version 1 and weather_api version 1

2022-09-29 02:52 UTC, AlexDeMichieli commented on code/rachel/python/pick_6/pick_6_1.py
> +print(f"Your final balance is {balance}.")
Missing v2

2022-09-29 02:53 UTC, AlexDeMichieli requested changes
Requesting Pick 6 v2 before merge.

2022-10-01 06:16 UTC, rachellindsay commented
I added Pick 6 version 2.

2022-10-04 03:13 UTC, ttajohnson approved these changes
Merging for Pick 6 completion.

2022-10-04 03:13 UTC, merged